canonical: https://gematik.de/fhir/atf
fhirVersion: 4.0.1 # https://www.hl7.org/fhir/valueset-FHIR-version.html
applyExtensionMetadataToRoot: false
FSHOnly: true
version: 1.0.0
dependencies:
  hl7.fhir.r4.core: 4.0.1