canonical: https://gematik.de/fhir/atf
fhirVersion: 4.0.1 # https://www.hl7.org/fhir/valueset-FHIR-version.html
name: App Transport Framework
id: de.gematik.fhir.atf
version: 1.4.0
status: active # draft | active | retired | unknown
releaseLabel: release # ci-build | draft | qa-preview | ballot | trial-use | release | update | normative+trial-use
copyrightYear: 2025
jurisdiction: urn:iso:std:iso:3166#DE "Germany" # https://www.hl7.org/fhir/valueset-jurisdiction.html

dependencies:
  de.basisprofil.r4: 1.5.3

applyExtensionMetadataToRoot: false

menu:
  Home: index.html
  Einführung: einfuehrung.html
  Anwendungsfall ATF:
    Nachrichtenaustausch: handshake.html
    Fehlerbehandlung: errorhandling.html
    Verwendung von ServiceIdentifier: serviceidentifier.html
    ATF via KIM: atf-kim.html
  Übergreifende Festlegungen:
    Methodik: methodik.html
    Versionierung: versionierung.html
  FHIR-Artefakte: artifacts.html
  Anhänge:
    Downloads: downloads.html
    Release Notes: releasenotes.html

parameters:
  path-pages:
    - input/content